name: CI/CD Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=$(which chromium-browser)" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV

      - name: Run Selenium test
        env:
          CHROME_BIN: ${{ env.CHROME_BIN }}
          CHROMEDRIVER_PATH: ${{ env.CHROMEDRIVER_PATH }}
        run: python test_example.py
